site_name: FinMind
site_url: https://finmind.github.io/FinMindDoc/
site_author: 'Sam'

copyright: 'Copyright'

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - python
    language: 'en'

repo_name: FinMind/FinMind
repo_url: https://github.com/FinMind/FinMind

nav:
    - Overview: 'index.md'
    - QuickStart: "quickstart.md"
    - TaiwanMarket:
        - DataList: "tutor/TaiwanMarket/DataList.md"
        - Technical: "tutor/TaiwanMarket/Technical.md"
        - Fundamental: "tutor/TaiwanMarket/Fundamental.md"
        - Chip: "tutor/TaiwanMarket/Chip.md"
        - Derivative: "tutor/TaiwanMarket/Derivative.md"
        - Others: "tutor/TaiwanMarket/Others.md"
    - UnitedStatesMarket:
        - DataList: "tutor/UnitedStatesMarket/DataList.md"
        - Technical: "tutor/UnitedStatesMarket/Technical.md"
    - UnitedKingdomMarket:
        - DataList: "tutor/UnitedKingdomMarket/DataList.md"
        - Technical: "tutor/UnitedKingdomMarket/Technical.md"
    - EuropeMarket:
        - DataList: "tutor/EuropeMarket/DataList.md"
        - Technical: "tutor/EuropeMarket/Technical.md"
    - JapanMarket:
        - DataList: "tutor/JapanMarket/DataList.md"
        - Technical: "tutor/JapanMarket/Technical.md"
    - ExchangeRate: "tutor/ExchangeRate.md"
    - InterestRate: "tutor/InterestRate.md"
    - Materials: "tutor/Materials.md"
    - Macroeconomy: "tutor/Macroeconomy.md"    
    - Versions:
        - What's New: "WhatIsNew.md"
    - Contact: "Contact.md"

markdown_extensions:
    - toc:
        permalink: true
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: docs
    - markdown.extensions.meta:
    - admonition
    - codehilite
    - extra
    - pymdownx.inlinehilite:
    - pymdownx.tabbed
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.gemoji
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format

