site_name: FinMind
site_url: https://finmind.github.io/FinMindDoc/
site_author: 'Sam'

copyright: 'Copyright'

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - python
    language: 'en'


nav:
    - Overview: 'index.md'
    - QuickStart: "quickstart.md"
    - Data:
        - Stock:
            - TaiwanStock: "tutor/TaiwanStock.md"
            - UnitedStatesStock: "tutor/UnitedStatesStock.md"
            - EuropeStock: "tutor/EuropeStock.md"
            - JapanStock: "tutor/JapanStock.md"
            - UnitedKingdomStock: "tutor/UnitedKingdomStock.md"
        - ExchangeRate: "tutor/ExchangeRate.md"
        - InterestRate: "tutor/InterestRate.md"
        - Materials: "tutor/Materials.md"
        - Macroeconomy: "tutor/Macroeconomy.md"

markdown_extensions:
    - toc:
        permalink: true
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: docs
    - markdown.extensions.meta:
    - admonition
    - codehilite
    - extra
    - pymdownx.inlinehilite:
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.gemoji
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format

