site_name: FinMind
site_url: https://finmind.github.io/FinMindDoc/
site_author: 'Sam'

copyright: 'Copyright'

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - python
    language: 'en'

repo_name: FinMind/FinMind
repo_url: https://github.com/FinMind/FinMind

extra:
  analytics:
    provider: google
    property: G-N2YPL1PVLE

nav:
    - 總覽: 'index.md'
    - 快速開始: "quickstart.md"
    - 登入: "login.md"
    - API 使用次數: "api_usage_count.md"
    - 資料集:
        - 台灣市場:
            - 總覽: "tutor/TaiwanMarket/DataList.md"
            - 技術面: "tutor/TaiwanMarket/Technical.md"
            - 籌碼面: "tutor/TaiwanMarket/Chip.md"
            - 基本面: "tutor/TaiwanMarket/Fundamental.md"
            - 衍生性金融商品: "tutor/TaiwanMarket/Derivative.md"
            - 即時資料: "tutor/TaiwanMarket/RealTime.md"
            - 可轉債: "tutor/TaiwanMarket/ConvertibleBond.md"
            - 其他: "tutor/TaiwanMarket/Others.md"
        - 美國市場:
            - 總覽: "tutor/UnitedStatesMarket/DataList.md"
            - 技術面: "tutor/UnitedStatesMarket/Technical.md"
        - 英國市場:
            - 總覽: "tutor/UnitedKingdomMarket/DataList.md"
            - 技術面: "tutor/UnitedKingdomMarket/Technical.md"
        - 歐洲市場:
            - 總覽: "tutor/EuropeMarket/DataList.md"
            - 技術面: "tutor/EuropeMarket/Technical.md"
        - 日本市場:
            - 總覽: "tutor/JapanMarket/DataList.md"
            - 技術面: "tutor/JapanMarket/Technical.md"
        - 匯率: "tutor/ExchangeRate.md"
        - 央行利率: "tutor/InterestRate.md"
        - 原物料市場: "tutor/Materials.md"
        - 美國國債: "tutor/GovernmentBondsYield.md"
        - 其他: "tutor/Others.md"
    - 量化工具:
        - 回測: "tutor/analysis/Backtesting.md"
        - 回測(引用外部 data): "tutor/analysis/BacktestingOtherData.md"
        - K 線: "tutor/analysis/Kline.md"
        - 客製化看盤儀表板: "tutor/analysis/CustomerDashboardWebServer.md"
        - 即時股市資訊 X 板塊圖: "tutor/analysis/SnapshotTreemap.md"
    - Versions:
        - What's New: "WhatIsNew.md"
        - Release Note: "release.md"
        - v4 (Latest): https://finmind.github.io/
        - v3: https://finmind.github.io/v3" target="_blank
    - 壓力測試: "StressTest.md"
    - 聯絡我們: "Contact.md"
    - 使用條款: "License.md"
    - 贊助我們: "Donate.md"
    - 官方網站: https://finmindtrade.com/" target="_blank

markdown_extensions:
    - toc:
        permalink: true
    - markdown.extensions.codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: docs
    - markdown.extensions.meta:
    - admonition
    - codehilite
    - extra
    - pymdownx.inlinehilite:
    - pymdownx.tabbed
    - pymdownx.emoji:
        emoji_index: !!python/name:pymdownx.emoji.gemoji
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'

