site_name: FinMind
site_url: https://finmind.github.io/FinMindDoc/
site_author: 'Sam'

copyright: 'Copyright'

theme:
    name: 'readthedocs'
    language: 'en'

nav:
    - Overview: 'index.md'
    - Data:
        dataset: "tutor/data.md"

extra:
    social:
        - type: 'github'
          link: 'https://github.com/FinMind/FinMind'
